### ISSUE TITLE
Issue with Encoder not present in libraries

### ISSUE THREAD

**Issue by JB2989** [nogasm/nogasm#4]
I 100% new to arduino so forgive my ignorance. I have uploaded the code and I get the error

"Arduino: 1.8.9 (Windows Store 1.8.21.0) (Windows 10), Board: "Arduino/Genuino Uno"

nogasm_code:45:21: error: Encoder.h: No such file or directory

compilation terminated.

exit status 1
Encoder.h: No such file or directory

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

After further research. I am not able to locate the Libraries required for this code. Could you please add this online? Thank you

**Comment by nogasm** [comment]
Sure thing. This uses a teensy LC, and in this case, encoder.h is one of great libraries written for that hardware, [available here.](https://github.com/PaulStoffregen/Encoder)

In the Arduino IDE, if you go to tools > include library > manage library and search "encoder" it will be one of the early results and is easiest to install there. You may first need the "teensyduino" addon installed, which you'll need for compilation anyway.

The other dependency you'll need is [Running Average, available here](https://github.com/RobTillaart/Arduino/tree/master/libraries/RunningAverage).

**Comment by JB2989** [comment]
Thank you so much for this information! I probably have downloaded similar.. but incorect libraries. I'll give these a shot in the next day and hopefully have it working!

Very impressive work I may add!

Have a great day.

________________________________

**Comment by nogasm** [comment]
No problem!
